@include('partials.widgets.mixed._widget-16', [
    'widgetNumber' => 4,
    'cardClass' => 'card card-xl-stretch mb-xl-8',
    'bodyClass' => 'card-body d-flex flex-column',
    'title' => 'Action Needed',
    'headingTitleWrapClass' => 'card-title align-items-start flex-column',
    'headingTitleTag' => 'h3',
    'headingTitleClass' => 'card-label fw-bold fs-3 mb-1',
    'headingSubtitle' => 'Complete your profile setup',
    'headingSubtitleClass' => 'text-muted fw-semibold fs-7',
    'menuVariant' => 'filter',
    'filterMenuUseCategoryIcon' => true,
    'menuId' => 'kt_menu_65a12148735bd',
    'chartWrapperClass' => 'flex-grow-1',
    'chartUseId' => false,
    'chartClass' => 'mixed-widget-4-chart',
    'chartAttr' => 'data-kt-chart-color',
    'chartColor' => 'primary',
    'chartStyle' => 'height: 200px',
    'contentClass' => 'pt-5',
    'textClass' => 'text-center fs-6 pb-5',
    'textIsHtml' => true,
    'textLine1' => '<span class="badge badge-light-danger fs-8">Notes:</span>&nbsp; Current sprint requires stakeholders',
    'textLine2' => 'to approve newly amended policies',
    'actionWrapperClass' => 'm-0',
    'actionHref' => '#',
    'actionClass' => 'btn btn-primary w-100 py-3',
    'showActionModal' => false,
    'actionText' => 'Take Action',
])
