@include('partials.widgets.mixed._widget-16', [
    'widgetNumber' => 17,
    'cardClass' => 'card card-xl-stretch mb-xl-8',
    'bodyClass' => 'card-body pt-5',
    'title' => 'User Base',
    'menuVariant' => 'payments',
    'chartWrapperClass' => 'd-flex flex-center w-100',
    'chartUseId' => false,
    'chartClass' => 'mixed-widget-17-chart',
    'chartAttr' => 'data-kt-chart-color',
    'chartColor' => 'primary',
    'chartStyle' => 'height: 300px',
    'contentClass' => 'text-center w-100 position-relative z-index-1',
    'contentStyle' => 'margin-top: -130px',
    'textClass' => 'fw-semibold fs-4 text-gray-500 mb-6',
    'textLine1' => 'Long before you sit down to put the',
    'textLine2' => 'make sure you breathe',
    'actionWrapperClass' => 'mb-9 mb-xxl-1',
    'actionClass' => 'btn btn-danger fw-semibold',
    'actionText' => 'Increase Users',
    'showFooter' => true,
    'footerClass' => 'card-footer d-flex flex-center py-5',
    'footerItems' => [
        [
            'wrapClass' => 'd-flex align-items-center flex-shrink-0 me-7 me-lg-12',
            'bulletClass' => 'bullet bullet-dot bg-primary me-2 h-10px w-10px',
            'labelClass' => 'fw-semibold text-gray-500 fs-6',
            'label' => 'Amount X',
        ],
        [
            'wrapClass' => 'd-flex align-items-center flex-shrink-0',
            'bulletClass' => 'bullet bullet-dot bg-success me-2 h-10px w-10px',
            'labelClass' => 'fw-semibold text-gray-500 fs-6',
            'label' => 'Amount Y',
        ],
    ],
])
