<?php

return [
    'title' => 'Konten Halaman',
    'title_en' => 'Page Content',
    'title_key' => 'wd_page_content',
    'route' => 'pagecontent',
    'icon' => 'ki-duotone ki-element-8 fs-2',
    'paths' => 2,
    'permissions' => ['read'],
    'roles' => ['admin'],
    'children' => [
        [
            'title' => 'Modul Halaman',
            'title_en' => 'Page Module',
            'title_key' => 'wd_page_module',
            'route' => 'pagecontent/page-module',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin'],
        ],
        [
            'title' => 'Audio Visual',
            'title_en' => 'Audio Visual',
            'title_key' => 'wd_audio_visual',
            'route' => 'pagecontent/audiovisual',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Slide Banner',
                    'title_en' => 'Slide Banner',
                    'title_key' => 'wd_slide_banner',
                    'route' => 'pagecontent/audiovisual/slide-banner',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Video',
                    'title_en' => 'Video',
                    'title_key' => 'wd_video',
                    'route' => 'pagecontent/audiovisual/video',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Gambar',
                    'title_en' => 'Image',
                    'title_key' => 'wd_image',
                    'route' => 'pagecontent/audiovisual/image',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Parallax',
                    'title_en' => 'Parallax',
                    'title_key' => 'wd_parallax',
                    'route' => 'pagecontent/audiovisual/parallax',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Ajakan Bertindak',
            'title_en' => 'Call to Action',
            'title_key' => 'wd_call_to_action',
            'route' => 'pagecontent/call-to-action',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin'],
        ],
        [
            'title' => 'Sub Navigasi',
            'title_en' => 'Sub Navigation',
            'title_key' => 'wd_sub_navigation',
            'route' => 'pagecontent/sub-navigation',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin'],
        ],
        [
            'title' => 'Iklan',
            'title_en' => 'Advertisements',
            'title_key' => 'wd_advertisements',
            'route' => 'pagecontent/advertisements',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Banner',
                    'title_en' => 'Banner',
                    'title_key' => 'wd_banner_advertisements',
                    'route' => 'pagecontent/advertisements/banner-advertisements',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Carousel',
                    'title_en' => 'Carousel',
                    'title_key' => 'wd_carousel_advertisements',
                    'route' => 'pagecontent/advertisements/carousel-advertisements',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
    ],
];
