<?php

return [
    'title' => 'Kurikulum',
    'title_en' => 'Curriculum',
    'title_key' => 'md_kurikulum',
    'route' => 'kurikulum',
    'icon' => 'ki-duotone ki-book-open fs-2',
    'paths' => 4,
    'permissions' => ['read'],
    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
    'children' => [
        [
            'title' => 'Perangkat Kurikulum',
            'title_en' => 'Curriculum Materials',
            'title_key' => 'md_perangkat_kurikulum',
            'route' => 'kurikulum/perangkatkurikulum',
            'permissions' => ['read'],
            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
            'children' => [
                [
                    'title' => 'Versi Kurikulum',
                    'title_en' => 'Curriculum Version',
                    'title_key' => 'md_versi_kurikulum',
                    'route' => 'kurikulum/perangkatkurikulum/versi-kurikulum',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Rombongan Belajar',
                    'title_en' => 'Class Group',
                    'title_key' => 'md_rombongan_belajar',
                    'route' => 'kurikulum/perangkatkurikulum/rombongan-belajar',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Wali Kelas',
                    'title_en' => 'Class Advisor',
                    'title_key' => 'md_wali_kelas',
                    'route' => 'kurikulum/perangkatkurikulum/wali-kelas',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Peserta Didik Rombel',
                    'title_en' => 'Student in Class Group',
                    'title_key' => 'md_peserta_didik_rombel',
                    'route' => 'kurikulum/perangkatkurikulum/peserta-didik-rombel',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Guru Wali',
                    'title_en' => 'Guardian Teachers',
                    'title_key' => 'md_guru_wali',
                    'route' => 'kurikulum/perangkatkurikulum/guru-wali',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
            ],
        ],
        [
            'title' => 'Data KBM',
            'title_en' => 'KBM Data',
            'title_key' => 'md_data_kbm',
            'route' => 'kurikulum/datakbm',
            'permissions' => ['read'],
            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
            'children' => [
                [
                    'title' => 'Mata Pelajaran',
                    'title_en' => 'Subject',
                    'title_key' => 'md_mata_pelajaran',
                    'route' => 'kurikulum/datakbm/mata-pelajaran',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Mata Pelajaran per Jurusan',
                    'title_en' => 'Subject by Major',
                    'title_key' => 'md_mata_pelajaran_jurusan',
                    'route' => 'kurikulum/datakbm/mata-pelajaran-jurusan',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Capaian Pembelajaran',
                    'title_en' => 'Learning Outcomes',
                    'title_key' => 'md_capaian_pembelajaran',
                    'route' => 'kurikulum/datakbm/capaian-pembelajaran',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'KBM Per Rombel',
                    'title_en' => 'KBM by Class Group',
                    'title_key' => 'md_kbm_per_rombel',
                    'route' => 'kurikulum/datakbm/kbm-per-rombel',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Kunci Data KBM',
                    'title_en' => 'KBM Data Keys',
                    'title_key' => 'md_kunci_data_kbm',
                    'route' => 'kurikulum/datakbm/kunci-datakbm',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],

            ],
        ],
        [
            'title' => 'Penjadwalan',
            'title_en' => 'Scheduling',
            'title_key' => 'md_penjadwalan',
            'route' => 'kurikulum/penjadwalan',
            'permissions' => ['read'],
            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
            'children' => [
                [
                    'title' => 'Hari Efektif',
                    'title_en' => 'Effective Days',
                    'title_key' => 'md_hari_efektif',
                    'route' => 'kurikulum/penjadwalan/hari-efektif',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Events',
                    'title_en' => 'Events',
                    'title_key' => 'md_events',
                    'route' => 'kurikulum/penjadwalan/events',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Jadwal Ngajar',
                    'title_en' => 'Teaching Schedule',
                    'title_key' => 'md_jadwal_ngajar',
                    'route' => 'kurikulum/penjadwalan/jadwalngajar',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                    'children' => [
                        [
                            'title' => 'Jadwal Mingguan',
                            'title_en' => 'Weekly Schedule',
                            'title_key' => 'md_jadwal_mingguan',
                            'route' => 'kurikulum/penjadwalan/jadwalngajar/jadwal-mingguan',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Jadwal per Rombel',
                            'title_en' => 'Schedule by Class Group',
                            'title_key' => 'md_jadwal_per_rombel',
                            'route' => 'kurikulum/penjadwalan/jadwalngajar/jadwal-per-rombel',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Jadwal per Guru',
                            'title_en' => 'Teaching Schedule',
                            'title_key' => 'md_jadwal_per_guru',
                            'route' => 'kurikulum/penjadwalan/jadwalngajar/jadwal-per-guru',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Jadwal Harian',
                            'title_en' => 'Daily Schedule',
                            'title_key' => 'md_jadwal_harian',
                            'route' => 'kurikulum/penjadwalan/jadwalngajar/jadwal-per-hari',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Perangkat Ujian',
            'title_en' => 'Examination Materials',
            'title_key' => 'md_perangkat_ujian',
            'route' => 'kurikulum/perangkatujian',
            'permissions' => ['read'],
            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
            'children' => [
                [
                    'title' => 'Identitas Ujian',
                    'title_en' => 'Examination Identity',
                    'title_key' => 'md_identitas_ujian',
                    'route' => 'kurikulum/perangkatujian/identitas-ujian',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Administrasi Ujian',
                    'title_en' => 'Examination Administration',
                    'title_key' => 'md_administrasi_ujian',
                    'route' => 'kurikulum/perangkatujian/administrasiujian',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                    'children' => [
                        [
                            'title' => 'Ruang Ujian',
                            'title_en' => 'Examination Rooms',
                            'title_key' => 'md_ruang_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/ruang-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Peserta Ujian',
                            'title_en' => 'Examination Participants',
                            'title_key' => 'md_peserta_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/peserta-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Jadwal Ujian',
                            'title_en' => 'Examination Schedule',
                            'title_key' => 'md_jadwal_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/jadwal-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Pengawas Ujian',
                            'title_en' => 'Examination Supervisors',
                            'title_key' => 'md_pengawas_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/pengawas-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Token Ujian',
                            'title_en' => 'Examination Tokens',
                            'title_key' => 'md_token_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/token-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Denah Ruangan',
                            'title_en' => 'Examination Room Layouts',
                            'title_key' => 'md_denah_ruangan',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/denah-ruangan',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Panitia Ujian',
                            'title_en' => 'Examination Committees',
                            'title_key' => 'md_panitia_ujian',
                            'route' => 'kurikulum/perangkatujian/administrasiujian/panitia-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                    ],
                ],
                [
                    'title' => 'Cetak Administrasi',
                    'title_en' => 'Print Administration',
                    'title_key' => 'md_cetak_administrasi',
                    'route' => 'kurikulum/perangkatujian/cetakadministrasi',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                    'children' => [
                        [
                            'title' => 'Berkas Administrasi',
                            'title_en' => 'Administrative Files',
                            'title_key' => 'md_berkas_administrasi',
                            'route' => 'kurikulum/perangkatujian/cetakadministrasi/berkas-administrasi',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                        [
                            'title' => 'Pelaksanaan Ujian',
                            'title_en' => 'Examination Implementation',
                            'title_key' => 'md_pelaksanaan_ujian',
                            'route' => 'kurikulum/perangkatujian/cetakadministrasi/pelaksanaan-ujian',
                            'permissions' => ['create', 'read', 'update', 'delete'],
                            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'title' => 'Dokumen Guru',
            'title_en' => 'Teacher Documents',
            'title_key' => 'md_dokumen_guru',
            'route' => 'kurikulum/dokumenguru',
            'permissions' => ['read'],
            'roles' => ['wakakurikulum', 'stafwakakurikulum'],
            'children' => [
                [
                    'title' => 'Guru Mata Pelajaran',
                    'title_en' => 'Subject Teachers',
                    'title_key' => 'md_guru_mata_pelajaran',
                    'route' => 'kurikulum/dokumenguru/arsip-gurumapel',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Wali Kelas',
                    'title_en' => 'Class Advisors',
                    'title_key' => 'md_wali_kelas',
                    'route' => 'kurikulum/dokumenguru/arsip-walikelas',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Guru Wali',
                    'title_en' => 'Guardian Teachers',
                    'title_key' => 'md_guru_wali',
                    'route' => 'kurikulum/dokumenguru/arsip-guruwali',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Administrasi KBM',
                    'title_en' => 'Academic Administration',
                    'title_key' => 'md_administrasi_kbm',
                    'route' => 'kurikulum/dokumenguru/administrasi-kbm',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
                [
                    'title' => 'Perangkat Ajar',
                    'title_en' => 'Teaching Materials',
                    'title_key' => 'md_perangkat_ajar',
                    'route' => 'kurikulum/dokumenguru/perangkat-ajar',
                    'permissions' => ['read'],
                    'roles' => ['wakakurikulum', 'stafwakakurikulum'],
                ],
            ],
        ],
    ],
];
