<?php

return [
    'title' => 'Manajemen Sekolah',
    'title_en' => 'School Management',
    'title_key' => 'md_manajemen_sekolah',
    'route' => 'manajemensekolah',
    'icon' => 'ki-duotone ki-faceid fs-2',
    'paths' => 6,
    'permissions' => ['read'],
    'roles' => ['admin'],
    'children' => [
        [
            'title' => 'Tahun Ajaran',
            'title_en' => 'Academic Year',
            'title_key' => 'md_tahun_ajaran',
            'route' => 'manajemensekolah/tahun-ajaran',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin'],
        ],
        [
            'title' => 'Identitas Sekolah',
            'title_en' => 'School Identity',
            'title_key' => 'md_identitas_sekolah',
            'route' => 'manajemensekolah/identitas-sekolah',
            'permissions' => ['create', 'read', 'update', 'delete'],
            'roles' => ['admin'],
        ],
        [
            'title' => 'Data Keahlian',
            'title_en' => 'Specialization Data',
            'title_key' => 'md_data_keahlian',
            'route' => 'manajemensekolah/datakeahlian',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Bidang Keahlian',
                    'title_en' => 'Specialization Field',
                    'title_key' => 'md_bidang_keahlian',
                    'route' => 'manajemensekolah/datakeahlian/bidang-keahlian',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Program Keahlian',
                    'title_en' => 'Specialization Program',
                    'title_key' => 'md_program_keahlian',
                    'route' => 'manajemensekolah/datakeahlian/program-keahlian',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Kompetensi Keahlian',
                    'title_en' => 'Specialization Competency',
                    'title_key' => 'md_kompetensi_keahlian',
                    'route' => 'manajemensekolah/datakeahlian/kompetensi-keahlian',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Data Personil',
            'title_en' => 'Personnel Data',
            'title_key' => 'md_data_personil',
            'route' => 'manajemensekolah/personil',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Personil Sekolah',
                    'title_en' => 'School Personnel',
                    'title_key' => 'md_personil_sekolah',
                    'route' => 'manajemensekolah/personil/personil-sekolah',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Peserta Didik',
                    'title_en' => 'Students',
                    'title_key' => 'md_peserta_didik',
                    'route' => 'manajemensekolah/personil/peserta-didik',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Tim Manajemen',
            'title_en' => 'Management Team',
            'title_key' => 'md_tim_manajemen',
            'route' => 'manajemensekolah/timmanajemen',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Kepala Sekolah',
                    'title_en' => 'School Principal',
                    'title_key' => 'md_kepala_sekolah',
                    'route' => 'manajemensekolah/timmanajemen/kepala-sekolah',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Wakil Kepala Sekolah',
                    'title_en' => 'Deputy School Principal',
                    'title_key' => 'md_wakil_kepala_sekolah',
                    'route' => 'manajemensekolah/timmanajemen/wakil-kepala-sekolah',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Ketua Program Studi',
                    'title_en' => 'Program Study Head',
                    'title_key' => 'md_ketua_program_studi',
                    'route' => 'manajemensekolah/timmanajemen/ketua-program-studi',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Jabatan Lain',
                    'title_en' => 'Other Positions',
                    'title_key' => 'md_jabatan_lain',
                    'route' => 'manajemensekolah/timmanajemen/jabatan-lain',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Pengembang Sekolah',
            'title_en' => 'School Developers',
            'title_key' => 'md_pengembang_sekolah',
            'route' => 'manajemensekolah/pengembangsekolah',
            'permissions' => ['read'],
            'roles' => ['admin', 'wakaps', 'stafwakaps'],
            'children' => [
                [
                    'title' => 'Manajemen Mutu',
                    'title_en' => 'Quality Management',
                    'title_key' => 'md_manajemen_mutu',
                    'route' => 'manajemensekolah/pengembangsekolah/manajemen-mutu',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin', 'wakaps', 'stafwakaps'],
                ],
                [
                    'title' => 'Dokumen Mutu',
                    'title_en' => 'Quality Documents',
                    'title_key' => 'md_dokumen_mutu',
                    'route' => 'manajemensekolah/pengembangsekolah/dokumen-mutu',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin', 'wakaps', 'stafwakaps'],
                ],
                [
                    'title' => 'Lampiran Dokumen',
                    'title_en' => 'Quality Document Attachments',
                    'title_key' => 'md_lampiran_dokumen',
                    'route' => 'manajemensekolah/pengembangsekolah/lampiran-dokumen',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin', 'wakaps', 'stafwakaps'],
                ],
            ],
        ],
    ],
];
