<?php

return [
    'title' => 'Web Site App',
    'title_en' => 'Web Site Application',
    'title_key' => 'md_aplikasi_web',
    'route' => 'websiteapp',
    'icon' => 'ki-duotone ki-abstract-20 fs-2',
    'paths' => 2,
    'permissions' => ['read'],
    'roles' => ['admin'],
    'children' => [
        [
            'title' => 'Upload Photo',
            'title_en' => 'Upload Photo',
            'title_key' => 'md_upload_photo',
            'route' => 'websiteapp/uploadphoto',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Photo Slide',
                    'title_en' => 'Photo Slide',
                    'title_key' => 'md_photo_slide',
                    'route' => 'websiteapp/uploadphoto/photo-slide',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Gallery Photo',
                    'title_en' => 'Gallery Photo',
                    'title_key' => 'md_gallery_photo',
                    'route' => 'websiteapp/uploadphoto/gallery-photo',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Photo Jurusan',
                    'title_en' => 'Major Photo',
                    'title_key' => 'md_photo_jurusan',
                    'route' => 'websiteapp/uploadphoto/photo-jurusan',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Logo Jurusan',
                    'title_en' => 'Major Logo',
                    'title_key' => 'md_logo_jurusan',
                    'route' => 'websiteapp/uploadphoto/logo-jurusan',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Photo Personil',
                    'title_en' => 'Personnel Photo',
                    'title_key' => 'md_photo_personil',
                    'route' => 'websiteapp/uploadphoto/photo-personil',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Halaman Web',
            'title_en' => 'Web Pages',
            'title_key' => 'md_halaman_web',
            'route' => 'websiteapp/halamanweb',
            'permissions' => ['read'],
            'roles' => ['admin'],
            'children' => [
                [
                    'title' => 'Refleksi MKS',
                    'title_en' => 'Reflection MKS',
                    'title_key' => 'md_refleksi_mks',
                    'route' => 'websiteapp/halamanweb/refleksi-mks',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Organisasi Sekolah',
                    'title_en' => 'School Organization',
                    'title_key' => 'md_organisasi_sekolah',
                    'route' => 'websiteapp/halamanweb/organisasi-sekolah',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Profil Jurusan',
                    'title_en' => 'Major Profile',
                    'title_key' => 'md_profil_jurusan',
                    'route' => 'websiteapp/halamanweb/profil-jurusan',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Team Pengembang',
                    'title_en' => 'Development Team',
                    'title_key' => 'md_team_pengembang',
                    'route' => 'websiteapp/halamanweb/team-pengembang',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Kumpulan Faqs',
                    'title_en' => 'Frequently Asked Questions',
                    'title_key' => 'md_kumpulan_faqs',
                    'route' => 'websiteapp/halamanweb/kumpulan-faqs',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Daily Messages',
                    'title_en' => 'Daily Messages',
                    'title_key' => 'md_daily_messages',
                    'route' => 'websiteapp/halamanweb/daily-messages',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Pengumuman',
                    'title_en' => 'Announcements',
                    'title_key' => 'md_pengumuman',
                    'route' => 'websiteapp/halamanweb/pengumuman',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
                [
                    'title' => 'Polling',
                    'title_en' => 'Polling',
                    'title_key' => 'md_polling',
                    'route' => 'websiteapp/halamanweb/polling',
                    'permissions' => ['create', 'read', 'update', 'delete'],
                    'roles' => ['admin'],
                ],
            ],
        ],
        [
            'title' => 'Informasi Sekolah',
            'title_en' => 'School Information',
            'title_key' => 'md_informasi_sekolah',
            'route' => 'websiteapp/informasi-sekolah',
            'permissions' => ['read'],
            'roles' => ['admin', 'guru'],
        ],
    ],
];
