<?php

return [
    'title' => 'Bimbingan Konseling',
    'title_en' => 'Counseling',
    'title_key' => 'ps_bpbk',
    'route' => 'bpbk',
    'icon' => 'ki-duotone ki-abstract-28 fs-2',
    'paths' => 2,
    'permissions' => ['read'],
    'roles' => ['bpbk'],
    'children' => [
        [
            'title' => 'Konseling Siswa',
            'title_en' => 'Student Counseling',
            'title_key' => 'ps_bpbk_konseling_siswa',
            'route' => 'bpbk/konseling-siswa',
            'permissions' => ['create', 'read', 'update', 'delete', 'sort'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Data KIP',
            'title_en' => 'KIP Data',
            'title_key' => 'ps_bpbk_data_kip',
            'route' => 'bpbk/data-kip',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Home Visit',
            'title_en' => 'Home Visit',
            'title_key' => 'ps_bpbk_home_visit',
            'route' => 'bpbk/home-visit',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Melanjutkan Kuliah',
            'title_en' => 'Continuing Education',
            'title_key' => 'ps_bpbk_melanjutkan_kuliah',
            'route' => 'bpbk/melanjutkan-kuliah',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Penelusuran Lulusan',
            'title_en' => 'Alumni Tracking',
            'title_key' => 'ps_bpbk_penelusuran_lulusan',
            'route' => 'bpbk/penelusuran-lulusan',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Anggaran',
            'title_en' => 'Budget',
            'title_key' => 'ps_bpbk_anggaran',
            'route' => 'bpbk/anggaran-bp-bk',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
        [
            'title' => 'Laporan',
            'title_en' => 'Report',
            'title_key' => 'ps_bpbk_laporan',
            'route' => 'bpbk/laporan-bp-bk',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['bpbk'],
        ],
    ],
];
