<?php

return [
    'title' => 'Tata Usaha',
    'title_en' => 'Administration',
    'title_key' => 'ps_tatausaha',
    'route' => 'ketatausahaan',
    'icon' => 'ki-duotone ki-abstract-28 fs-2',
    'paths' => 2,
    'permissions' => ['read'],
    'roles' => ['tatausaha'],
    'children' => [
        [
            'title' => 'Persuratan',
            'title_en' => 'Correspondence',
            'title_key' => 'ps_tatausaha_persuratan',
            'route' => 'ketatausahaan/persuratan',
            'permissions' => ['create', 'read', 'update', 'delete', 'sort'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Kesiswaan',
            'title_en' => 'Student Affairs',
            'title_key' => 'ps_tatausaha_kesiswaan',
            'route' => 'ketatausahaan/kesiswaan',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Kepegawaian',
            'title_en' => 'Human Resources',
            'title_key' => 'ps_tatausaha_kepegawaian',
            'route' => 'ketatausahaan/kepegawaian',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Sarana Prasarana',
            'title_en' => 'Facilities',
            'title_key' => 'ps_tatausaha_sarana_prasarana',
            'route' => 'ketatausahaan/sarana-prasarana',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Manajemen Barang',
            'title_en' => 'Inventory Management',
            'title_key' => 'ps_tatausaha_manajemen_barang',
            'route' => 'ketatausahaan/manajemen-barang',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Agenda',
            'title_en' => 'Agenda',
            'title_key' => 'ps_tatausaha_agenda',
            'route' => 'ketatausahaan/agenda-ketatausahaan',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Anggaran',
            'title_en' => 'Budget',
            'title_key' => 'ps_tatausaha_anggaran',
            'route' => 'ketatausahaan/anggaran-ketatausahaan',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
        [
            'title' => 'Laporan',
            'title_en' => 'Report',
            'title_key' => 'ps_tatausaha_laporan',
            'route' => 'ketatausahaan/laporan-ketatausahaan',
            'permissions' => ['create', 'read', 'update'],
            'roles' => ['tatausaha'],
        ],
    ],
];
